/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterInstructorRouteImport } from './routes/register-instructor'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ConditionsGeneralesRouteImport } from './routes/conditions-generales'
import { Route as BecomeInstructorRouteImport } from './routes/become-instructor'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ProtectedInstructorRouteRouteImport } from './routes/_protected/instructor/route'
import { Route as ProtectedClientRouteRouteImport } from './routes/_protected/client/route'
import { Route as ProtectedAdminRouteRouteImport } from './routes/_protected/admin/route'
import { Route as ProtectedInstructorProfileRouteImport } from './routes/_protected/instructor/profile'
import { Route as ProtectedInstructorNotificationsRouteImport } from './routes/_protected/instructor/notifications'
import { Route as ProtectedInstructorDashboardRouteImport } from './routes/_protected/instructor/dashboard'
import { Route as ProtectedInstructorCoursesRouteImport } from './routes/_protected/instructor/courses'
import { Route as ProtectedClientProfileRouteImport } from './routes/_protected/client/profile'
import { Route as ProtectedClientPaymentHistoryRouteImport } from './routes/_protected/client/payment-history'
import { Route as ProtectedClientNotificationsRouteImport } from './routes/_protected/client/notifications'
import { Route as ProtectedClientMessagingRouteImport } from './routes/_protected/client/messaging'
import { Route as ProtectedClientCertificatesRouteImport } from './routes/_protected/client/certificates'
import { Route as ProtectedAdminProfileRouteImport } from './routes/_protected/admin/profile'
import { Route as ProtectedAdminNotificationsRouteImport } from './routes/_protected/admin/notifications'
import { Route as ProtectedAdminInstructorsRouteImport } from './routes/_protected/admin/instructors'
import { Route as ProtectedClientPostsRouteRouteImport } from './routes/_protected/client/posts/route'
import { Route as ProtectedAdminPostsRouteRouteImport } from './routes/_protected/admin/posts/route'
import { Route as ProtectedAdminPaymentsRouteRouteImport } from './routes/_protected/admin/payments/route'
import { Route as ProtectedClientDashboardIndexRouteImport } from './routes/_protected/client/dashboard/index'
import { Route as ProtectedClientCatalogIndexRouteImport } from './routes/_protected/client/catalog/index'
import { Route as ProtectedAdminDashboardIndexRouteImport } from './routes/_protected/admin/dashboard/index'
import { Route as ProtectedAdminCoursesIndexRouteImport } from './routes/_protected/admin/courses/index'
import { Route as ProtectedInstructorCoursesCourseIdRouteImport } from './routes/_protected/instructor/courses.$courseId'
import { Route as ProtectedClientPlayerCourseIdRouteImport } from './routes/_protected/client/player/$courseId'
import { Route as ProtectedClientCheckoutCourseIdRouteImport } from './routes/_protected/client/checkout/$courseId'
import { Route as ProtectedClientCatalogCourseIdRouteImport } from './routes/_protected/client/catalog/$courseId'
import { Route as ProtectedAdminCoursesCourseIdRouteImport } from './routes/_protected/admin/courses/$courseId'

const RegisterInstructorRoute = RegisterInstructorRouteImport.update({
  id: '/register-instructor',
  path: '/register-instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsGeneralesRoute = ConditionsGeneralesRouteImport.update({
  id: '/conditions-generales',
  path: '/conditions-generales',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeInstructorRoute = BecomeInstructorRouteImport.update({
  id: '/become-instructor',
  path: '/become-instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedInstructorRouteRoute =
  ProtectedInstructorRouteRouteImport.update({
    id: '/instructor',
    path: '/instructor',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedClientRouteRoute = ProtectedClientRouteRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminRouteRoute = ProtectedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedInstructorProfileRoute =
  ProtectedInstructorProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProtectedInstructorRouteRoute,
  } as any)
const ProtectedInstructorNotificationsRoute =
  ProtectedInstructorNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ProtectedInstructorRouteRoute,
  } as any)
const ProtectedInstructorDashboardRoute =
  ProtectedInstructorDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedInstructorRouteRoute,
  } as any)
const ProtectedInstructorCoursesRoute =
  ProtectedInstructorCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => ProtectedInstructorRouteRoute,
  } as any)
const ProtectedClientProfileRoute = ProtectedClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedClientRouteRoute,
} as any)
const ProtectedClientPaymentHistoryRoute =
  ProtectedClientPaymentHistoryRouteImport.update({
    id: '/payment-history',
    path: '/payment-history',
    getParentRoute: () => ProtectedClientRouteRoute,
  } as any)
const ProtectedClientNotificationsRoute =
  ProtectedClientNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ProtectedClientRouteRoute,
  } as any)
const ProtectedClientMessagingRoute =
  ProtectedClientMessagingRouteImport.update({
    id: '/messaging',
    path: '/messaging',
    getParentRoute: () => ProtectedClientRouteRoute,
  } as any)
const ProtectedClientCertificatesRoute =
  ProtectedClientCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => ProtectedClientRouteRoute,
  } as any)
const ProtectedAdminProfileRoute = ProtectedAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const ProtectedAdminNotificationsRoute =
  ProtectedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminInstructorsRoute =
  ProtectedAdminInstructorsRouteImport.update({
    id: '/instructors',
    path: '/instructors',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedClientPostsRouteRoute =
  ProtectedClientPostsRouteRouteImport.update({
    id: '/posts',
    path: '/posts',
    getParentRoute: () => ProtectedClientRouteRoute,
  } as any)
const ProtectedAdminPostsRouteRoute =
  ProtectedAdminPostsRouteRouteImport.update({
    id: '/posts',
    path: '/posts',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminPaymentsRouteRoute =
  ProtectedAdminPaymentsRouteRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedClientDashboardIndexRoute =
  ProtectedClientDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedClientRouteRoute,
  } as any)
const ProtectedClientCatalogIndexRoute =
  ProtectedClientCatalogIndexRouteImport.update({
    id: '/catalog/',
    path: '/catalog/',
    getParentRoute: () => ProtectedClientRouteRoute,
  } as any)
const ProtectedAdminDashboardIndexRoute =
  ProtectedAdminDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminCoursesIndexRoute =
  ProtectedAdminCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedInstructorCoursesCourseIdRoute =
  ProtectedInstructorCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => ProtectedInstructorCoursesRoute,
  } as any)
const ProtectedClientPlayerCourseIdRoute =
  ProtectedClientPlayerCourseIdRouteImport.update({
    id: '/player/$courseId',
    path: '/player/$courseId',
    getParentRoute: () => ProtectedClientRouteRoute,
  } as any)
const ProtectedClientCheckoutCourseIdRoute =
  ProtectedClientCheckoutCourseIdRouteImport.update({
    id: '/checkout/$courseId',
    path: '/checkout/$courseId',
    getParentRoute: () => ProtectedClientRouteRoute,
  } as any)
const ProtectedClientCatalogCourseIdRoute =
  ProtectedClientCatalogCourseIdRouteImport.update({
    id: '/catalog/$courseId',
    path: '/catalog/$courseId',
    getParentRoute: () => ProtectedClientRouteRoute,
  } as any)
const ProtectedAdminCoursesCourseIdRoute =
  ProtectedAdminCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-instructor': typeof BecomeInstructorRoute
  '/conditions-generales': typeof ConditionsGeneralesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/register-instructor': typeof RegisterInstructorRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/client': typeof ProtectedClientRouteRouteWithChildren
  '/instructor': typeof ProtectedInstructorRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/payments': typeof ProtectedAdminPaymentsRouteRoute
  '/admin/posts': typeof ProtectedAdminPostsRouteRoute
  '/client/posts': typeof ProtectedClientPostsRouteRoute
  '/admin/instructors': typeof ProtectedAdminInstructorsRoute
  '/admin/notifications': typeof ProtectedAdminNotificationsRoute
  '/admin/profile': typeof ProtectedAdminProfileRoute
  '/client/certificates': typeof ProtectedClientCertificatesRoute
  '/client/messaging': typeof ProtectedClientMessagingRoute
  '/client/notifications': typeof ProtectedClientNotificationsRoute
  '/client/payment-history': typeof ProtectedClientPaymentHistoryRoute
  '/client/profile': typeof ProtectedClientProfileRoute
  '/instructor/courses': typeof ProtectedInstructorCoursesRouteWithChildren
  '/instructor/dashboard': typeof ProtectedInstructorDashboardRoute
  '/instructor/notifications': typeof ProtectedInstructorNotificationsRoute
  '/instructor/profile': typeof ProtectedInstructorProfileRoute
  '/admin/courses/$courseId': typeof ProtectedAdminCoursesCourseIdRoute
  '/client/catalog/$courseId': typeof ProtectedClientCatalogCourseIdRoute
  '/client/checkout/$courseId': typeof ProtectedClientCheckoutCourseIdRoute
  '/client/player/$courseId': typeof ProtectedClientPlayerCourseIdRoute
  '/instructor/courses/$courseId': typeof ProtectedInstructorCoursesCourseIdRoute
  '/admin/courses': typeof ProtectedAdminCoursesIndexRoute
  '/admin/dashboard': typeof ProtectedAdminDashboardIndexRoute
  '/client/catalog': typeof ProtectedClientCatalogIndexRoute
  '/client/dashboard': typeof ProtectedClientDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-instructor': typeof BecomeInstructorRoute
  '/conditions-generales': typeof ConditionsGeneralesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/register-instructor': typeof RegisterInstructorRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/client': typeof ProtectedClientRouteRouteWithChildren
  '/instructor': typeof ProtectedInstructorRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/payments': typeof ProtectedAdminPaymentsRouteRoute
  '/admin/posts': typeof ProtectedAdminPostsRouteRoute
  '/client/posts': typeof ProtectedClientPostsRouteRoute
  '/admin/instructors': typeof ProtectedAdminInstructorsRoute
  '/admin/notifications': typeof ProtectedAdminNotificationsRoute
  '/admin/profile': typeof ProtectedAdminProfileRoute
  '/client/certificates': typeof ProtectedClientCertificatesRoute
  '/client/messaging': typeof ProtectedClientMessagingRoute
  '/client/notifications': typeof ProtectedClientNotificationsRoute
  '/client/payment-history': typeof ProtectedClientPaymentHistoryRoute
  '/client/profile': typeof ProtectedClientProfileRoute
  '/instructor/courses': typeof ProtectedInstructorCoursesRouteWithChildren
  '/instructor/dashboard': typeof ProtectedInstructorDashboardRoute
  '/instructor/notifications': typeof ProtectedInstructorNotificationsRoute
  '/instructor/profile': typeof ProtectedInstructorProfileRoute
  '/admin/courses/$courseId': typeof ProtectedAdminCoursesCourseIdRoute
  '/client/catalog/$courseId': typeof ProtectedClientCatalogCourseIdRoute
  '/client/checkout/$courseId': typeof ProtectedClientCheckoutCourseIdRoute
  '/client/player/$courseId': typeof ProtectedClientPlayerCourseIdRoute
  '/instructor/courses/$courseId': typeof ProtectedInstructorCoursesCourseIdRoute
  '/admin/courses': typeof ProtectedAdminCoursesIndexRoute
  '/admin/dashboard': typeof ProtectedAdminDashboardIndexRoute
  '/client/catalog': typeof ProtectedClientCatalogIndexRoute
  '/client/dashboard': typeof ProtectedClientDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/become-instructor': typeof BecomeInstructorRoute
  '/conditions-generales': typeof ConditionsGeneralesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/register-instructor': typeof RegisterInstructorRoute
  '/_protected/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/_protected/client': typeof ProtectedClientRouteRouteWithChildren
  '/_protected/instructor': typeof ProtectedInstructorRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_protected/admin/payments': typeof ProtectedAdminPaymentsRouteRoute
  '/_protected/admin/posts': typeof ProtectedAdminPostsRouteRoute
  '/_protected/client/posts': typeof ProtectedClientPostsRouteRoute
  '/_protected/admin/instructors': typeof ProtectedAdminInstructorsRoute
  '/_protected/admin/notifications': typeof ProtectedAdminNotificationsRoute
  '/_protected/admin/profile': typeof ProtectedAdminProfileRoute
  '/_protected/client/certificates': typeof ProtectedClientCertificatesRoute
  '/_protected/client/messaging': typeof ProtectedClientMessagingRoute
  '/_protected/client/notifications': typeof ProtectedClientNotificationsRoute
  '/_protected/client/payment-history': typeof ProtectedClientPaymentHistoryRoute
  '/_protected/client/profile': typeof ProtectedClientProfileRoute
  '/_protected/instructor/courses': typeof ProtectedInstructorCoursesRouteWithChildren
  '/_protected/instructor/dashboard': typeof ProtectedInstructorDashboardRoute
  '/_protected/instructor/notifications': typeof ProtectedInstructorNotificationsRoute
  '/_protected/instructor/profile': typeof ProtectedInstructorProfileRoute
  '/_protected/admin/courses/$courseId': typeof ProtectedAdminCoursesCourseIdRoute
  '/_protected/client/catalog/$courseId': typeof ProtectedClientCatalogCourseIdRoute
  '/_protected/client/checkout/$courseId': typeof ProtectedClientCheckoutCourseIdRoute
  '/_protected/client/player/$courseId': typeof ProtectedClientPlayerCourseIdRoute
  '/_protected/instructor/courses/$courseId': typeof ProtectedInstructorCoursesCourseIdRoute
  '/_protected/admin/courses/': typeof ProtectedAdminCoursesIndexRoute
  '/_protected/admin/dashboard/': typeof ProtectedAdminDashboardIndexRoute
  '/_protected/client/catalog/': typeof ProtectedClientCatalogIndexRoute
  '/_protected/client/dashboard/': typeof ProtectedClientDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-instructor'
    | '/conditions-generales'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/register-instructor'
    | '/admin'
    | '/client'
    | '/instructor'
    | '/login'
    | '/register'
    | '/demo/tanstack-query'
    | '/admin/payments'
    | '/admin/posts'
    | '/client/posts'
    | '/admin/instructors'
    | '/admin/notifications'
    | '/admin/profile'
    | '/client/certificates'
    | '/client/messaging'
    | '/client/notifications'
    | '/client/payment-history'
    | '/client/profile'
    | '/instructor/courses'
    | '/instructor/dashboard'
    | '/instructor/notifications'
    | '/instructor/profile'
    | '/admin/courses/$courseId'
    | '/client/catalog/$courseId'
    | '/client/checkout/$courseId'
    | '/client/player/$courseId'
    | '/instructor/courses/$courseId'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/client/catalog'
    | '/client/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-instructor'
    | '/conditions-generales'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/register-instructor'
    | '/admin'
    | '/client'
    | '/instructor'
    | '/login'
    | '/register'
    | '/demo/tanstack-query'
    | '/admin/payments'
    | '/admin/posts'
    | '/client/posts'
    | '/admin/instructors'
    | '/admin/notifications'
    | '/admin/profile'
    | '/client/certificates'
    | '/client/messaging'
    | '/client/notifications'
    | '/client/payment-history'
    | '/client/profile'
    | '/instructor/courses'
    | '/instructor/dashboard'
    | '/instructor/notifications'
    | '/instructor/profile'
    | '/admin/courses/$courseId'
    | '/client/catalog/$courseId'
    | '/client/checkout/$courseId'
    | '/client/player/$courseId'
    | '/instructor/courses/$courseId'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/client/catalog'
    | '/client/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/become-instructor'
    | '/conditions-generales'
    | '/confidentialite'
    | '/contact'
    | '/mentions-legales'
    | '/register-instructor'
    | '/_protected/admin'
    | '/_protected/client'
    | '/_protected/instructor'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/demo/tanstack-query'
    | '/_protected/admin/payments'
    | '/_protected/admin/posts'
    | '/_protected/client/posts'
    | '/_protected/admin/instructors'
    | '/_protected/admin/notifications'
    | '/_protected/admin/profile'
    | '/_protected/client/certificates'
    | '/_protected/client/messaging'
    | '/_protected/client/notifications'
    | '/_protected/client/payment-history'
    | '/_protected/client/profile'
    | '/_protected/instructor/courses'
    | '/_protected/instructor/dashboard'
    | '/_protected/instructor/notifications'
    | '/_protected/instructor/profile'
    | '/_protected/admin/courses/$courseId'
    | '/_protected/client/catalog/$courseId'
    | '/_protected/client/checkout/$courseId'
    | '/_protected/client/player/$courseId'
    | '/_protected/instructor/courses/$courseId'
    | '/_protected/admin/courses/'
    | '/_protected/admin/dashboard/'
    | '/_protected/client/catalog/'
    | '/_protected/client/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  BecomeInstructorRoute: typeof BecomeInstructorRoute
  ConditionsGeneralesRoute: typeof ConditionsGeneralesRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  RegisterInstructorRoute: typeof RegisterInstructorRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-instructor': {
      id: '/register-instructor'
      path: '/register-instructor'
      fullPath: '/register-instructor'
      preLoaderRoute: typeof RegisterInstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-generales': {
      id: '/conditions-generales'
      path: '/conditions-generales'
      fullPath: '/conditions-generales'
      preLoaderRoute: typeof ConditionsGeneralesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-instructor': {
      id: '/become-instructor'
      path: '/become-instructor'
      fullPath: '/become-instructor'
      preLoaderRoute: typeof BecomeInstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/instructor': {
      id: '/_protected/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof ProtectedInstructorRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/client': {
      id: '/_protected/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ProtectedClientRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/instructor/profile': {
      id: '/_protected/instructor/profile'
      path: '/profile'
      fullPath: '/instructor/profile'
      preLoaderRoute: typeof ProtectedInstructorProfileRouteImport
      parentRoute: typeof ProtectedInstructorRouteRoute
    }
    '/_protected/instructor/notifications': {
      id: '/_protected/instructor/notifications'
      path: '/notifications'
      fullPath: '/instructor/notifications'
      preLoaderRoute: typeof ProtectedInstructorNotificationsRouteImport
      parentRoute: typeof ProtectedInstructorRouteRoute
    }
    '/_protected/instructor/dashboard': {
      id: '/_protected/instructor/dashboard'
      path: '/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof ProtectedInstructorDashboardRouteImport
      parentRoute: typeof ProtectedInstructorRouteRoute
    }
    '/_protected/instructor/courses': {
      id: '/_protected/instructor/courses'
      path: '/courses'
      fullPath: '/instructor/courses'
      preLoaderRoute: typeof ProtectedInstructorCoursesRouteImport
      parentRoute: typeof ProtectedInstructorRouteRoute
    }
    '/_protected/client/profile': {
      id: '/_protected/client/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ProtectedClientProfileRouteImport
      parentRoute: typeof ProtectedClientRouteRoute
    }
    '/_protected/client/payment-history': {
      id: '/_protected/client/payment-history'
      path: '/payment-history'
      fullPath: '/client/payment-history'
      preLoaderRoute: typeof ProtectedClientPaymentHistoryRouteImport
      parentRoute: typeof ProtectedClientRouteRoute
    }
    '/_protected/client/notifications': {
      id: '/_protected/client/notifications'
      path: '/notifications'
      fullPath: '/client/notifications'
      preLoaderRoute: typeof ProtectedClientNotificationsRouteImport
      parentRoute: typeof ProtectedClientRouteRoute
    }
    '/_protected/client/messaging': {
      id: '/_protected/client/messaging'
      path: '/messaging'
      fullPath: '/client/messaging'
      preLoaderRoute: typeof ProtectedClientMessagingRouteImport
      parentRoute: typeof ProtectedClientRouteRoute
    }
    '/_protected/client/certificates': {
      id: '/_protected/client/certificates'
      path: '/certificates'
      fullPath: '/client/certificates'
      preLoaderRoute: typeof ProtectedClientCertificatesRouteImport
      parentRoute: typeof ProtectedClientRouteRoute
    }
    '/_protected/admin/profile': {
      id: '/_protected/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof ProtectedAdminProfileRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/notifications': {
      id: '/_protected/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof ProtectedAdminNotificationsRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/instructors': {
      id: '/_protected/admin/instructors'
      path: '/instructors'
      fullPath: '/admin/instructors'
      preLoaderRoute: typeof ProtectedAdminInstructorsRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/client/posts': {
      id: '/_protected/client/posts'
      path: '/posts'
      fullPath: '/client/posts'
      preLoaderRoute: typeof ProtectedClientPostsRouteRouteImport
      parentRoute: typeof ProtectedClientRouteRoute
    }
    '/_protected/admin/posts': {
      id: '/_protected/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof ProtectedAdminPostsRouteRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/payments': {
      id: '/_protected/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof ProtectedAdminPaymentsRouteRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/client/dashboard/': {
      id: '/_protected/client/dashboard/'
      path: '/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ProtectedClientDashboardIndexRouteImport
      parentRoute: typeof ProtectedClientRouteRoute
    }
    '/_protected/client/catalog/': {
      id: '/_protected/client/catalog/'
      path: '/catalog'
      fullPath: '/client/catalog'
      preLoaderRoute: typeof ProtectedClientCatalogIndexRouteImport
      parentRoute: typeof ProtectedClientRouteRoute
    }
    '/_protected/admin/dashboard/': {
      id: '/_protected/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof ProtectedAdminDashboardIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/courses/': {
      id: '/_protected/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof ProtectedAdminCoursesIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/instructor/courses/$courseId': {
      id: '/_protected/instructor/courses/$courseId'
      path: '/$courseId'
      fullPath: '/instructor/courses/$courseId'
      preLoaderRoute: typeof ProtectedInstructorCoursesCourseIdRouteImport
      parentRoute: typeof ProtectedInstructorCoursesRoute
    }
    '/_protected/client/player/$courseId': {
      id: '/_protected/client/player/$courseId'
      path: '/player/$courseId'
      fullPath: '/client/player/$courseId'
      preLoaderRoute: typeof ProtectedClientPlayerCourseIdRouteImport
      parentRoute: typeof ProtectedClientRouteRoute
    }
    '/_protected/client/checkout/$courseId': {
      id: '/_protected/client/checkout/$courseId'
      path: '/checkout/$courseId'
      fullPath: '/client/checkout/$courseId'
      preLoaderRoute: typeof ProtectedClientCheckoutCourseIdRouteImport
      parentRoute: typeof ProtectedClientRouteRoute
    }
    '/_protected/client/catalog/$courseId': {
      id: '/_protected/client/catalog/$courseId'
      path: '/catalog/$courseId'
      fullPath: '/client/catalog/$courseId'
      preLoaderRoute: typeof ProtectedClientCatalogCourseIdRouteImport
      parentRoute: typeof ProtectedClientRouteRoute
    }
    '/_protected/admin/courses/$courseId': {
      id: '/_protected/admin/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof ProtectedAdminCoursesCourseIdRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
  }
}

interface ProtectedAdminRouteRouteChildren {
  ProtectedAdminPaymentsRouteRoute: typeof ProtectedAdminPaymentsRouteRoute
  ProtectedAdminPostsRouteRoute: typeof ProtectedAdminPostsRouteRoute
  ProtectedAdminInstructorsRoute: typeof ProtectedAdminInstructorsRoute
  ProtectedAdminNotificationsRoute: typeof ProtectedAdminNotificationsRoute
  ProtectedAdminProfileRoute: typeof ProtectedAdminProfileRoute
  ProtectedAdminCoursesCourseIdRoute: typeof ProtectedAdminCoursesCourseIdRoute
  ProtectedAdminCoursesIndexRoute: typeof ProtectedAdminCoursesIndexRoute
  ProtectedAdminDashboardIndexRoute: typeof ProtectedAdminDashboardIndexRoute
}

const ProtectedAdminRouteRouteChildren: ProtectedAdminRouteRouteChildren = {
  ProtectedAdminPaymentsRouteRoute: ProtectedAdminPaymentsRouteRoute,
  ProtectedAdminPostsRouteRoute: ProtectedAdminPostsRouteRoute,
  ProtectedAdminInstructorsRoute: ProtectedAdminInstructorsRoute,
  ProtectedAdminNotificationsRoute: ProtectedAdminNotificationsRoute,
  ProtectedAdminProfileRoute: ProtectedAdminProfileRoute,
  ProtectedAdminCoursesCourseIdRoute: ProtectedAdminCoursesCourseIdRoute,
  ProtectedAdminCoursesIndexRoute: ProtectedAdminCoursesIndexRoute,
  ProtectedAdminDashboardIndexRoute: ProtectedAdminDashboardIndexRoute,
}

const ProtectedAdminRouteRouteWithChildren =
  ProtectedAdminRouteRoute._addFileChildren(ProtectedAdminRouteRouteChildren)

interface ProtectedClientRouteRouteChildren {
  ProtectedClientPostsRouteRoute: typeof ProtectedClientPostsRouteRoute
  ProtectedClientCertificatesRoute: typeof ProtectedClientCertificatesRoute
  ProtectedClientMessagingRoute: typeof ProtectedClientMessagingRoute
  ProtectedClientNotificationsRoute: typeof ProtectedClientNotificationsRoute
  ProtectedClientPaymentHistoryRoute: typeof ProtectedClientPaymentHistoryRoute
  ProtectedClientProfileRoute: typeof ProtectedClientProfileRoute
  ProtectedClientCatalogCourseIdRoute: typeof ProtectedClientCatalogCourseIdRoute
  ProtectedClientCheckoutCourseIdRoute: typeof ProtectedClientCheckoutCourseIdRoute
  ProtectedClientPlayerCourseIdRoute: typeof ProtectedClientPlayerCourseIdRoute
  ProtectedClientCatalogIndexRoute: typeof ProtectedClientCatalogIndexRoute
  ProtectedClientDashboardIndexRoute: typeof ProtectedClientDashboardIndexRoute
}

const ProtectedClientRouteRouteChildren: ProtectedClientRouteRouteChildren = {
  ProtectedClientPostsRouteRoute: ProtectedClientPostsRouteRoute,
  ProtectedClientCertificatesRoute: ProtectedClientCertificatesRoute,
  ProtectedClientMessagingRoute: ProtectedClientMessagingRoute,
  ProtectedClientNotificationsRoute: ProtectedClientNotificationsRoute,
  ProtectedClientPaymentHistoryRoute: ProtectedClientPaymentHistoryRoute,
  ProtectedClientProfileRoute: ProtectedClientProfileRoute,
  ProtectedClientCatalogCourseIdRoute: ProtectedClientCatalogCourseIdRoute,
  ProtectedClientCheckoutCourseIdRoute: ProtectedClientCheckoutCourseIdRoute,
  ProtectedClientPlayerCourseIdRoute: ProtectedClientPlayerCourseIdRoute,
  ProtectedClientCatalogIndexRoute: ProtectedClientCatalogIndexRoute,
  ProtectedClientDashboardIndexRoute: ProtectedClientDashboardIndexRoute,
}

const ProtectedClientRouteRouteWithChildren =
  ProtectedClientRouteRoute._addFileChildren(ProtectedClientRouteRouteChildren)

interface ProtectedInstructorCoursesRouteChildren {
  ProtectedInstructorCoursesCourseIdRoute: typeof ProtectedInstructorCoursesCourseIdRoute
}

const ProtectedInstructorCoursesRouteChildren: ProtectedInstructorCoursesRouteChildren =
  {
    ProtectedInstructorCoursesCourseIdRoute:
      ProtectedInstructorCoursesCourseIdRoute,
  }

const ProtectedInstructorCoursesRouteWithChildren =
  ProtectedInstructorCoursesRoute._addFileChildren(
    ProtectedInstructorCoursesRouteChildren,
  )

interface ProtectedInstructorRouteRouteChildren {
  ProtectedInstructorCoursesRoute: typeof ProtectedInstructorCoursesRouteWithChildren
  ProtectedInstructorDashboardRoute: typeof ProtectedInstructorDashboardRoute
  ProtectedInstructorNotificationsRoute: typeof ProtectedInstructorNotificationsRoute
  ProtectedInstructorProfileRoute: typeof ProtectedInstructorProfileRoute
}

const ProtectedInstructorRouteRouteChildren: ProtectedInstructorRouteRouteChildren =
  {
    ProtectedInstructorCoursesRoute:
      ProtectedInstructorCoursesRouteWithChildren,
    ProtectedInstructorDashboardRoute: ProtectedInstructorDashboardRoute,
    ProtectedInstructorNotificationsRoute:
      ProtectedInstructorNotificationsRoute,
    ProtectedInstructorProfileRoute: ProtectedInstructorProfileRoute,
  }

const ProtectedInstructorRouteRouteWithChildren =
  ProtectedInstructorRouteRoute._addFileChildren(
    ProtectedInstructorRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedAdminRouteRoute: typeof ProtectedAdminRouteRouteWithChildren
  ProtectedClientRouteRoute: typeof ProtectedClientRouteRouteWithChildren
  ProtectedInstructorRouteRoute: typeof ProtectedInstructorRouteRouteWithChildren
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAdminRouteRoute: ProtectedAdminRouteRouteWithChildren,
  ProtectedClientRouteRoute: ProtectedClientRouteRouteWithChildren,
  ProtectedInstructorRouteRoute: ProtectedInstructorRouteRouteWithChildren,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  BecomeInstructorRoute: BecomeInstructorRoute,
  ConditionsGeneralesRoute: ConditionsGeneralesRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  RegisterInstructorRoute: RegisterInstructorRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
