/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ProtectedTeacherRouteRouteImport } from './routes/_protected/teacher/route'
import { Route as ProtectedSuperAdminRouteRouteImport } from './routes/_protected/super-admin/route'
import { Route as ProtectedStudentRouteRouteImport } from './routes/_protected/student/route'
import { Route as ProtectedAdminRouteRouteImport } from './routes/_protected/admin/route'
import { Route as ProtectedAdminUsersRouteRouteImport } from './routes/_protected/admin/users/route'
import { Route as ProtectedTeacherDashboardIndexRouteImport } from './routes/_protected/teacher/dashboard/index'
import { Route as ProtectedSuperAdminModulesIndexRouteImport } from './routes/_protected/super-admin/modules/index'
import { Route as ProtectedSuperAdminLessonsIndexRouteImport } from './routes/_protected/super-admin/lessons/index'
import { Route as ProtectedSuperAdminEnrollmentsIndexRouteImport } from './routes/_protected/super-admin/enrollments/index'
import { Route as ProtectedSuperAdminDashboardIndexRouteImport } from './routes/_protected/super-admin/dashboard/index'
import { Route as ProtectedSuperAdminCoursesIndexRouteImport } from './routes/_protected/super-admin/courses/index'
import { Route as ProtectedSuperAdminCourseSessionsIndexRouteImport } from './routes/_protected/super-admin/course-sessions/index'
import { Route as ProtectedSuperAdminCategoriesIndexRouteImport } from './routes/_protected/super-admin/categories/index'
import { Route as ProtectedStudentDashboardIndexRouteImport } from './routes/_protected/student/dashboard/index'
import { Route as ProtectedStudentCoursesIndexRouteImport } from './routes/_protected/student/courses/index'
import { Route as ProtectedAdminRoomsIndexRouteImport } from './routes/_protected/admin/rooms/index'
import { Route as ProtectedAdminPeriodsIndexRouteImport } from './routes/_protected/admin/periods/index'
import { Route as ProtectedAdminDashboardIndexRouteImport } from './routes/_protected/admin/dashboard/index'
import { Route as ProtectedStudentCoursesCourseIdRouteImport } from './routes/_protected/student/courses/$courseId'
import { Route as ProtectedAdminUsersStudentsRouteRouteImport } from './routes/_protected/admin/users/students/route'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTeacherRouteRoute = ProtectedTeacherRouteRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSuperAdminRouteRoute =
  ProtectedSuperAdminRouteRouteImport.update({
    id: '/super-admin',
    path: '/super-admin',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedStudentRouteRoute = ProtectedStudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminRouteRoute = ProtectedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminUsersRouteRoute =
  ProtectedAdminUsersRouteRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedTeacherDashboardIndexRoute =
  ProtectedTeacherDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedTeacherRouteRoute,
  } as any)
const ProtectedSuperAdminModulesIndexRoute =
  ProtectedSuperAdminModulesIndexRouteImport.update({
    id: '/modules/',
    path: '/modules/',
    getParentRoute: () => ProtectedSuperAdminRouteRoute,
  } as any)
const ProtectedSuperAdminLessonsIndexRoute =
  ProtectedSuperAdminLessonsIndexRouteImport.update({
    id: '/lessons/',
    path: '/lessons/',
    getParentRoute: () => ProtectedSuperAdminRouteRoute,
  } as any)
const ProtectedSuperAdminEnrollmentsIndexRoute =
  ProtectedSuperAdminEnrollmentsIndexRouteImport.update({
    id: '/enrollments/',
    path: '/enrollments/',
    getParentRoute: () => ProtectedSuperAdminRouteRoute,
  } as any)
const ProtectedSuperAdminDashboardIndexRoute =
  ProtectedSuperAdminDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedSuperAdminRouteRoute,
  } as any)
const ProtectedSuperAdminCoursesIndexRoute =
  ProtectedSuperAdminCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => ProtectedSuperAdminRouteRoute,
  } as any)
const ProtectedSuperAdminCourseSessionsIndexRoute =
  ProtectedSuperAdminCourseSessionsIndexRouteImport.update({
    id: '/course-sessions/',
    path: '/course-sessions/',
    getParentRoute: () => ProtectedSuperAdminRouteRoute,
  } as any)
const ProtectedSuperAdminCategoriesIndexRoute =
  ProtectedSuperAdminCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => ProtectedSuperAdminRouteRoute,
  } as any)
const ProtectedStudentDashboardIndexRoute =
  ProtectedStudentDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedStudentRouteRoute,
  } as any)
const ProtectedStudentCoursesIndexRoute =
  ProtectedStudentCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => ProtectedStudentRouteRoute,
  } as any)
const ProtectedAdminRoomsIndexRoute =
  ProtectedAdminRoomsIndexRouteImport.update({
    id: '/rooms/',
    path: '/rooms/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminPeriodsIndexRoute =
  ProtectedAdminPeriodsIndexRouteImport.update({
    id: '/periods/',
    path: '/periods/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminDashboardIndexRoute =
  ProtectedAdminDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedStudentCoursesCourseIdRoute =
  ProtectedStudentCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => ProtectedStudentRouteRoute,
  } as any)
const ProtectedAdminUsersStudentsRouteRoute =
  ProtectedAdminUsersStudentsRouteRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => ProtectedAdminUsersRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/student': typeof ProtectedStudentRouteRouteWithChildren
  '/super-admin': typeof ProtectedSuperAdminRouteRouteWithChildren
  '/teacher': typeof ProtectedTeacherRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/admin/users': typeof ProtectedAdminUsersRouteRouteWithChildren
  '/admin/users/students': typeof ProtectedAdminUsersStudentsRouteRoute
  '/student/courses/$courseId': typeof ProtectedStudentCoursesCourseIdRoute
  '/admin/dashboard/': typeof ProtectedAdminDashboardIndexRoute
  '/admin/periods/': typeof ProtectedAdminPeriodsIndexRoute
  '/admin/rooms/': typeof ProtectedAdminRoomsIndexRoute
  '/student/courses/': typeof ProtectedStudentCoursesIndexRoute
  '/student/dashboard/': typeof ProtectedStudentDashboardIndexRoute
  '/super-admin/categories/': typeof ProtectedSuperAdminCategoriesIndexRoute
  '/super-admin/course-sessions/': typeof ProtectedSuperAdminCourseSessionsIndexRoute
  '/super-admin/courses/': typeof ProtectedSuperAdminCoursesIndexRoute
  '/super-admin/dashboard/': typeof ProtectedSuperAdminDashboardIndexRoute
  '/super-admin/enrollments/': typeof ProtectedSuperAdminEnrollmentsIndexRoute
  '/super-admin/lessons/': typeof ProtectedSuperAdminLessonsIndexRoute
  '/super-admin/modules/': typeof ProtectedSuperAdminModulesIndexRoute
  '/teacher/dashboard/': typeof ProtectedTeacherDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/student': typeof ProtectedStudentRouteRouteWithChildren
  '/super-admin': typeof ProtectedSuperAdminRouteRouteWithChildren
  '/teacher': typeof ProtectedTeacherRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/admin/users': typeof ProtectedAdminUsersRouteRouteWithChildren
  '/admin/users/students': typeof ProtectedAdminUsersStudentsRouteRoute
  '/student/courses/$courseId': typeof ProtectedStudentCoursesCourseIdRoute
  '/admin/dashboard': typeof ProtectedAdminDashboardIndexRoute
  '/admin/periods': typeof ProtectedAdminPeriodsIndexRoute
  '/admin/rooms': typeof ProtectedAdminRoomsIndexRoute
  '/student/courses': typeof ProtectedStudentCoursesIndexRoute
  '/student/dashboard': typeof ProtectedStudentDashboardIndexRoute
  '/super-admin/categories': typeof ProtectedSuperAdminCategoriesIndexRoute
  '/super-admin/course-sessions': typeof ProtectedSuperAdminCourseSessionsIndexRoute
  '/super-admin/courses': typeof ProtectedSuperAdminCoursesIndexRoute
  '/super-admin/dashboard': typeof ProtectedSuperAdminDashboardIndexRoute
  '/super-admin/enrollments': typeof ProtectedSuperAdminEnrollmentsIndexRoute
  '/super-admin/lessons': typeof ProtectedSuperAdminLessonsIndexRoute
  '/super-admin/modules': typeof ProtectedSuperAdminModulesIndexRoute
  '/teacher/dashboard': typeof ProtectedTeacherDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/_protected/student': typeof ProtectedStudentRouteRouteWithChildren
  '/_protected/super-admin': typeof ProtectedSuperAdminRouteRouteWithChildren
  '/_protected/teacher': typeof ProtectedTeacherRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_protected/admin/users': typeof ProtectedAdminUsersRouteRouteWithChildren
  '/_protected/admin/users/students': typeof ProtectedAdminUsersStudentsRouteRoute
  '/_protected/student/courses/$courseId': typeof ProtectedStudentCoursesCourseIdRoute
  '/_protected/admin/dashboard/': typeof ProtectedAdminDashboardIndexRoute
  '/_protected/admin/periods/': typeof ProtectedAdminPeriodsIndexRoute
  '/_protected/admin/rooms/': typeof ProtectedAdminRoomsIndexRoute
  '/_protected/student/courses/': typeof ProtectedStudentCoursesIndexRoute
  '/_protected/student/dashboard/': typeof ProtectedStudentDashboardIndexRoute
  '/_protected/super-admin/categories/': typeof ProtectedSuperAdminCategoriesIndexRoute
  '/_protected/super-admin/course-sessions/': typeof ProtectedSuperAdminCourseSessionsIndexRoute
  '/_protected/super-admin/courses/': typeof ProtectedSuperAdminCoursesIndexRoute
  '/_protected/super-admin/dashboard/': typeof ProtectedSuperAdminDashboardIndexRoute
  '/_protected/super-admin/enrollments/': typeof ProtectedSuperAdminEnrollmentsIndexRoute
  '/_protected/super-admin/lessons/': typeof ProtectedSuperAdminLessonsIndexRoute
  '/_protected/super-admin/modules/': typeof ProtectedSuperAdminModulesIndexRoute
  '/_protected/teacher/dashboard/': typeof ProtectedTeacherDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/student'
    | '/super-admin'
    | '/teacher'
    | '/login'
    | '/register'
    | '/admin/users'
    | '/admin/users/students'
    | '/student/courses/$courseId'
    | '/admin/dashboard/'
    | '/admin/periods/'
    | '/admin/rooms/'
    | '/student/courses/'
    | '/student/dashboard/'
    | '/super-admin/categories/'
    | '/super-admin/course-sessions/'
    | '/super-admin/courses/'
    | '/super-admin/dashboard/'
    | '/super-admin/enrollments/'
    | '/super-admin/lessons/'
    | '/super-admin/modules/'
    | '/teacher/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/student'
    | '/super-admin'
    | '/teacher'
    | '/login'
    | '/register'
    | '/admin/users'
    | '/admin/users/students'
    | '/student/courses/$courseId'
    | '/admin/dashboard'
    | '/admin/periods'
    | '/admin/rooms'
    | '/student/courses'
    | '/student/dashboard'
    | '/super-admin/categories'
    | '/super-admin/course-sessions'
    | '/super-admin/courses'
    | '/super-admin/dashboard'
    | '/super-admin/enrollments'
    | '/super-admin/lessons'
    | '/super-admin/modules'
    | '/teacher/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/admin'
    | '/_protected/student'
    | '/_protected/super-admin'
    | '/_protected/teacher'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_protected/admin/users'
    | '/_protected/admin/users/students'
    | '/_protected/student/courses/$courseId'
    | '/_protected/admin/dashboard/'
    | '/_protected/admin/periods/'
    | '/_protected/admin/rooms/'
    | '/_protected/student/courses/'
    | '/_protected/student/dashboard/'
    | '/_protected/super-admin/categories/'
    | '/_protected/super-admin/course-sessions/'
    | '/_protected/super-admin/courses/'
    | '/_protected/super-admin/dashboard/'
    | '/_protected/super-admin/enrollments/'
    | '/_protected/super-admin/lessons/'
    | '/_protected/super-admin/modules/'
    | '/_protected/teacher/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/teacher': {
      id: '/_protected/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof ProtectedTeacherRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/super-admin': {
      id: '/_protected/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof ProtectedSuperAdminRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/student': {
      id: '/_protected/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof ProtectedStudentRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin/users': {
      id: '/_protected/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof ProtectedAdminUsersRouteRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/teacher/dashboard/': {
      id: '/_protected/teacher/dashboard/'
      path: '/dashboard'
      fullPath: '/teacher/dashboard/'
      preLoaderRoute: typeof ProtectedTeacherDashboardIndexRouteImport
      parentRoute: typeof ProtectedTeacherRouteRoute
    }
    '/_protected/super-admin/modules/': {
      id: '/_protected/super-admin/modules/'
      path: '/modules'
      fullPath: '/super-admin/modules/'
      preLoaderRoute: typeof ProtectedSuperAdminModulesIndexRouteImport
      parentRoute: typeof ProtectedSuperAdminRouteRoute
    }
    '/_protected/super-admin/lessons/': {
      id: '/_protected/super-admin/lessons/'
      path: '/lessons'
      fullPath: '/super-admin/lessons/'
      preLoaderRoute: typeof ProtectedSuperAdminLessonsIndexRouteImport
      parentRoute: typeof ProtectedSuperAdminRouteRoute
    }
    '/_protected/super-admin/enrollments/': {
      id: '/_protected/super-admin/enrollments/'
      path: '/enrollments'
      fullPath: '/super-admin/enrollments/'
      preLoaderRoute: typeof ProtectedSuperAdminEnrollmentsIndexRouteImport
      parentRoute: typeof ProtectedSuperAdminRouteRoute
    }
    '/_protected/super-admin/dashboard/': {
      id: '/_protected/super-admin/dashboard/'
      path: '/dashboard'
      fullPath: '/super-admin/dashboard/'
      preLoaderRoute: typeof ProtectedSuperAdminDashboardIndexRouteImport
      parentRoute: typeof ProtectedSuperAdminRouteRoute
    }
    '/_protected/super-admin/courses/': {
      id: '/_protected/super-admin/courses/'
      path: '/courses'
      fullPath: '/super-admin/courses/'
      preLoaderRoute: typeof ProtectedSuperAdminCoursesIndexRouteImport
      parentRoute: typeof ProtectedSuperAdminRouteRoute
    }
    '/_protected/super-admin/course-sessions/': {
      id: '/_protected/super-admin/course-sessions/'
      path: '/course-sessions'
      fullPath: '/super-admin/course-sessions/'
      preLoaderRoute: typeof ProtectedSuperAdminCourseSessionsIndexRouteImport
      parentRoute: typeof ProtectedSuperAdminRouteRoute
    }
    '/_protected/super-admin/categories/': {
      id: '/_protected/super-admin/categories/'
      path: '/categories'
      fullPath: '/super-admin/categories/'
      preLoaderRoute: typeof ProtectedSuperAdminCategoriesIndexRouteImport
      parentRoute: typeof ProtectedSuperAdminRouteRoute
    }
    '/_protected/student/dashboard/': {
      id: '/_protected/student/dashboard/'
      path: '/dashboard'
      fullPath: '/student/dashboard/'
      preLoaderRoute: typeof ProtectedStudentDashboardIndexRouteImport
      parentRoute: typeof ProtectedStudentRouteRoute
    }
    '/_protected/student/courses/': {
      id: '/_protected/student/courses/'
      path: '/courses'
      fullPath: '/student/courses/'
      preLoaderRoute: typeof ProtectedStudentCoursesIndexRouteImport
      parentRoute: typeof ProtectedStudentRouteRoute
    }
    '/_protected/admin/rooms/': {
      id: '/_protected/admin/rooms/'
      path: '/rooms'
      fullPath: '/admin/rooms/'
      preLoaderRoute: typeof ProtectedAdminRoomsIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/periods/': {
      id: '/_protected/admin/periods/'
      path: '/periods'
      fullPath: '/admin/periods/'
      preLoaderRoute: typeof ProtectedAdminPeriodsIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/dashboard/': {
      id: '/_protected/admin/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof ProtectedAdminDashboardIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/student/courses/$courseId': {
      id: '/_protected/student/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/student/courses/$courseId'
      preLoaderRoute: typeof ProtectedStudentCoursesCourseIdRouteImport
      parentRoute: typeof ProtectedStudentRouteRoute
    }
    '/_protected/admin/users/students': {
      id: '/_protected/admin/users/students'
      path: '/students'
      fullPath: '/admin/users/students'
      preLoaderRoute: typeof ProtectedAdminUsersStudentsRouteRouteImport
      parentRoute: typeof ProtectedAdminUsersRouteRoute
    }
  }
}

interface ProtectedAdminUsersRouteRouteChildren {
  ProtectedAdminUsersStudentsRouteRoute: typeof ProtectedAdminUsersStudentsRouteRoute
}

const ProtectedAdminUsersRouteRouteChildren: ProtectedAdminUsersRouteRouteChildren =
  {
    ProtectedAdminUsersStudentsRouteRoute:
      ProtectedAdminUsersStudentsRouteRoute,
  }

const ProtectedAdminUsersRouteRouteWithChildren =
  ProtectedAdminUsersRouteRoute._addFileChildren(
    ProtectedAdminUsersRouteRouteChildren,
  )

interface ProtectedAdminRouteRouteChildren {
  ProtectedAdminUsersRouteRoute: typeof ProtectedAdminUsersRouteRouteWithChildren
  ProtectedAdminDashboardIndexRoute: typeof ProtectedAdminDashboardIndexRoute
  ProtectedAdminPeriodsIndexRoute: typeof ProtectedAdminPeriodsIndexRoute
  ProtectedAdminRoomsIndexRoute: typeof ProtectedAdminRoomsIndexRoute
}

const ProtectedAdminRouteRouteChildren: ProtectedAdminRouteRouteChildren = {
  ProtectedAdminUsersRouteRoute: ProtectedAdminUsersRouteRouteWithChildren,
  ProtectedAdminDashboardIndexRoute: ProtectedAdminDashboardIndexRoute,
  ProtectedAdminPeriodsIndexRoute: ProtectedAdminPeriodsIndexRoute,
  ProtectedAdminRoomsIndexRoute: ProtectedAdminRoomsIndexRoute,
}

const ProtectedAdminRouteRouteWithChildren =
  ProtectedAdminRouteRoute._addFileChildren(ProtectedAdminRouteRouteChildren)

interface ProtectedStudentRouteRouteChildren {
  ProtectedStudentCoursesCourseIdRoute: typeof ProtectedStudentCoursesCourseIdRoute
  ProtectedStudentCoursesIndexRoute: typeof ProtectedStudentCoursesIndexRoute
  ProtectedStudentDashboardIndexRoute: typeof ProtectedStudentDashboardIndexRoute
}

const ProtectedStudentRouteRouteChildren: ProtectedStudentRouteRouteChildren = {
  ProtectedStudentCoursesCourseIdRoute: ProtectedStudentCoursesCourseIdRoute,
  ProtectedStudentCoursesIndexRoute: ProtectedStudentCoursesIndexRoute,
  ProtectedStudentDashboardIndexRoute: ProtectedStudentDashboardIndexRoute,
}

const ProtectedStudentRouteRouteWithChildren =
  ProtectedStudentRouteRoute._addFileChildren(
    ProtectedStudentRouteRouteChildren,
  )

interface ProtectedSuperAdminRouteRouteChildren {
  ProtectedSuperAdminCategoriesIndexRoute: typeof ProtectedSuperAdminCategoriesIndexRoute
  ProtectedSuperAdminCourseSessionsIndexRoute: typeof ProtectedSuperAdminCourseSessionsIndexRoute
  ProtectedSuperAdminCoursesIndexRoute: typeof ProtectedSuperAdminCoursesIndexRoute
  ProtectedSuperAdminDashboardIndexRoute: typeof ProtectedSuperAdminDashboardIndexRoute
  ProtectedSuperAdminEnrollmentsIndexRoute: typeof ProtectedSuperAdminEnrollmentsIndexRoute
  ProtectedSuperAdminLessonsIndexRoute: typeof ProtectedSuperAdminLessonsIndexRoute
  ProtectedSuperAdminModulesIndexRoute: typeof ProtectedSuperAdminModulesIndexRoute
}

const ProtectedSuperAdminRouteRouteChildren: ProtectedSuperAdminRouteRouteChildren =
  {
    ProtectedSuperAdminCategoriesIndexRoute:
      ProtectedSuperAdminCategoriesIndexRoute,
    ProtectedSuperAdminCourseSessionsIndexRoute:
      ProtectedSuperAdminCourseSessionsIndexRoute,
    ProtectedSuperAdminCoursesIndexRoute: ProtectedSuperAdminCoursesIndexRoute,
    ProtectedSuperAdminDashboardIndexRoute:
      ProtectedSuperAdminDashboardIndexRoute,
    ProtectedSuperAdminEnrollmentsIndexRoute:
      ProtectedSuperAdminEnrollmentsIndexRoute,
    ProtectedSuperAdminLessonsIndexRoute: ProtectedSuperAdminLessonsIndexRoute,
    ProtectedSuperAdminModulesIndexRoute: ProtectedSuperAdminModulesIndexRoute,
  }

const ProtectedSuperAdminRouteRouteWithChildren =
  ProtectedSuperAdminRouteRoute._addFileChildren(
    ProtectedSuperAdminRouteRouteChildren,
  )

interface ProtectedTeacherRouteRouteChildren {
  ProtectedTeacherDashboardIndexRoute: typeof ProtectedTeacherDashboardIndexRoute
}

const ProtectedTeacherRouteRouteChildren: ProtectedTeacherRouteRouteChildren = {
  ProtectedTeacherDashboardIndexRoute: ProtectedTeacherDashboardIndexRoute,
}

const ProtectedTeacherRouteRouteWithChildren =
  ProtectedTeacherRouteRoute._addFileChildren(
    ProtectedTeacherRouteRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedAdminRouteRoute: typeof ProtectedAdminRouteRouteWithChildren
  ProtectedStudentRouteRoute: typeof ProtectedStudentRouteRouteWithChildren
  ProtectedSuperAdminRouteRoute: typeof ProtectedSuperAdminRouteRouteWithChildren
  ProtectedTeacherRouteRoute: typeof ProtectedTeacherRouteRouteWithChildren
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAdminRouteRoute: ProtectedAdminRouteRouteWithChildren,
  ProtectedStudentRouteRoute: ProtectedStudentRouteRouteWithChildren,
  ProtectedSuperAdminRouteRoute: ProtectedSuperAdminRouteRouteWithChildren,
  ProtectedTeacherRouteRoute: ProtectedTeacherRouteRouteWithChildren,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
